### ISSUE TITLE
[Potential Bug]: Station Mules are reluctant to move items

### ISSUE THREAD

**Issue by empZealoth** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#107]
**Describe the Bug**
I've got a Station A producing Hull parts, Station B producing Graphene and some overproduction from Claytronics intermediaries, connected via a Warehouse station
The issue is, I've got 4 station mules assigned to station A and a massive glut of Hull Parts there (30k over sell limit!), yet most of the time 2-3 mules are idling, at best maybe two do a Hull Parts run, usually one does Energy cells and one Hull parts
Similar thing happens with station B, usually 2 out of 3 mules are idling, despite having tons of items to move

**Expected Behaviour**
I'd like the Mules to be go to work on the gluts more agressively! (It kinda feels like the dispatcher is very very slow to react - on the order of real time of several minutes

**Version Info**
 - X4 Foundations : Public, both DLC
 - Mules Extended Mod : [Steam Workshop ]

**Screenshots**
![obraz](https://user-images.githubusercontent.com/10992509/112401011-e61fd500-8d09-11eb-8a06-d4517e42f041.png)

**Additional context**
Using VRO and Factions Enhanced, some other misc mods

**Comment by empZealoth** [comment]
It took almost an hour for them to get to work. Is this just because of trying to avoid performance hit?
Maybe it would be nice to have some way to temporarily force more aggression (or at least add very blatant info to the how2 page on expected reaction times!)

**Comment by bhayden53** [comment]
can you post a screenshot of the logical overview of the destination warehouse

**Comment by empZealoth** [comment]
![obraz](https://user-images.githubusercontent.com/10992509/112403847-7b719800-8d0f-11eb-8c1d-049464c53782.png)
![obraz](https://user-images.githubusercontent.com/10992509/112403872-8a584a80-8d0f-11eb-941a-a7b977ab1926.png)
![obraz](https://user-images.githubusercontent.com/10992509/112403906-9cd28400-8d0f-11eb-809f-2f24cfa11acd.png)
![obraz](https://user-images.githubusercontent.com/10992509/112404091-f8047680-8d0f-11eb-9598-ce4a6dd43e09.png)

(The massive amount of sales in Hull Part factory comes from me getting desperate and unlocking NPC trade - but you can see how badly it got clogged up)
Do the mules use pricing as priority signals?
I'm usually just having one Mule running the parts for some reason - also, Station B mules dont take warehouse Hull Parts to it's buildstorage :/ (two way trade is on!)

**Comment by bhayden53** [comment]
I was looking for the funding levels; on the one that I can see the station account it is extremely low. What is the funding level on the warehouse?

Mules work by retrieving trade orders from the game; one thing I've noticed in 4.0 is that the "buy offers" in the UI can be very misleading; the trade offers under the hood can be significantly affected by lack of funding. When you don't have enough money in the account, the manager will split up what you do have across some or all of the wares; so it may look like the station want's to buy 100k of something, but if there's not enough funding the actual order that the mule evaluates ends up being for like 5k (as an example).

So if your warehouse is not pretty loaded with cash, mules can't really work.

In previous versions of X4, it was definitely not safe to "override" the manager just because we knew the storage levels; the game would cancel trades on us and overall it just produced a buggy experience. I don't know if it would be better in 4.0, but my guess is we're pretty stuck with the budget limitations; so my suggestion is to start your warehouse small otherwise the budget will be like 200 million and it'll be forever until everything is working the way you think it should.

**Comment by empZealoth** [comment]
I set all my stations to 500k right now (kinda broke, have to keep buying miners to feed the claytronics factory)
So, even though the mules dont actually move money, i need to have enough funds to "buy" all the items i want to move?

**Comment by bhayden53** [comment]
not necessarily "all" of the items but yes, you need enough money for the station manager to actually think he can buy things

**Comment by Misunderstood-Wookiee** [comment]
You'd think the engine would just prioritise what he can afford and what
stock levels is already there or needed silly egosoft ai
