### ISSUE TITLE
supply mule looking for trades / not moving certain wares

### ISSUE THREAD

**Issue by Midnitewolf** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#112]
I have another issue.  Well two issues but I think they are related.

Using Supply Mule, I have two issues.  

First, many times when I set everything up, the ship assigned just sits there looking for trades.  This happens randomly and doesn't happen to every ship.  I had 4 L traders all sitting in the same system, all assigned to one station, all getting the same goods.  2 worked flawlessly, 2 refused to do anything but look for trades.  I finally got one of the two to work by leaving everything to default, having him start trading, then change the location (assigned him to station) and some of the filters (made it so he wouldn't use my own stations as a supplier) but the other one refuses to trade, period and this solution doesn't always work.  I have several M class transporters assigned to the same station that also seem to outright refuse to trade anything while having about 15+ all with the same orders, all working flawlessly.

The second part is a straight up refusal to trade certain wares.  I have a combination Wharf/Shipyard that is importing all it needs to build ships.    I set up the mules and all the necessary items pulled except three.   Smart Chips, Missile Components and Advanced Composites.  All of these exist for sale close as two jumps away and are selling way lower than my buy price.   Smart Chips are in short supply though still available.  Missile Components and Advanced Composites are both in good supply to great supply however so it isn't an issue due to lack of supply.

I can also set up repeat order trades at the locations selling these items and the very same ship that refuse to trade via the mule, trade fine between my station and the selling station without issue so it isn't a ship bug.

**Comment by bhayden53** [comment]
This sounds to me like either a funding issue, or a supply/demand issue where the ones that are finding the trades are making reservations that are stopping the others from working.

If you want me to look further I'll need a debug log. You can launch with a script like this:
https://gist.github.com/MattMcFarland/4c2f5cdd4657e91239cf7285b5d3b726

(take note of needing to change to -scriptlogfiles

Then there will be some individual mule logs buried in something like Documents/egosoft/x4/logs/mulesextended/<ship-id>.txt. Send me a log for the mules that you think aren't working correctly.

**Comment by Chh2tx** [comment]
Not to hijack this from OP, but I was noticing some traders not making any effort to fulfill some orders, and I've narrowed it down to the mincapacity. The quantity remaining (or in my case the total demand requested -- MREs) was below the min capacity for this station. Since I only use M or higher traders, it just never get's fulfilled.

**It's possible that the OP (highlighting his L freighter usage), similar to myself, no longer have any orders that meet the min capacity of the trader in use.** So the remaining orders don't get fulfilled, or in my case, my order for MREs will never fill cause the required amount for this station will never exceed the mincapacity for my M freighters.

By my math, my Baldric has a mincapacity of 4120 MRE units of the 5350 it could carry. As my Wharf tops out at 4008 MREs, this order will never be fulfilled for MREs via supply mules unless I throw ships with lower capacity. Perhaps this is 'ideal'. I've just avoided S couriers due to their fragility.

I'm not using trade stations currently, just fleet of supply mules (two for different ware types) that keep my stations supplied. I had been questioning why they seemed to idle, despite orders existing and appears this capacity rule is the reason.

I'm not sure the best solution, or perhaps if stock level of a ware could somehow influence it's priority even if that meant a half full ship. It would seem to be more advantageous to fill to keep stock levels from running completely out vs fulfilling stock by profit margin alone. Similarly, I noticed my M traders making repeated runs for Silicon Carbide and computronic substrate, when the station is out of Microlattice. Instead of using stock levels to try to balance, I had to wait until they exhausted the higher profit Silicon Carbide before they switched to microlattice. That stalled ship production for a longer period of time.  If I queue up many ships, they produce in bursts due to this as the order fulfillment works top down by profit and not stock.

Any thoughts on an option prioritizing out of stock/low stock for supply mules over profit and/or mincapacity? If min stock is met, then it reverts to topping off based on it's existing logic. That'd potentially even distribution and allow larger freighters to still fullfill low quantity items, but only if the need is great (out of stock/low stock). Or maybe I just need to suck it up and add some S freighters.

**Comment by bhayden53** [comment]
So the way it used to work was that the max trades option effectively changed the minimum trade size.... with a default setting of 5, that meant that supply mules would allow trades that were only 20% of their cargo.

However, we found that after a major refactoring of our code, the max trades setting was causing a bug, where after the first trade was queued up, the game would cancel our aiscript and relinquish control to the trade orders that were created. So I fixed max trades to 1 as a workaround, because we don't know a fix for sure for that one.

So then with the setting at 1, of course some trades can just never be completed because the wares don't fit into the cargo hold with an even number. So then I fixed the setting at 75% of cargo.

The only true workaround now is either an "allow low volume" option, like the station mule has, or just a slider, like the travel mule has. I am leaning slider as I tend to prefer giving the user more options.

Changes to params are somewhat major changes and so I've been dragging my feet on this one. I suppose at this time I am leaning towards deprecating the max trades setting altogether and rethinking it at a future date, if both @Galaxy-Spam and myself ever dive deep back into writing code.

**Comment by Midnitewolf** [comment]
Thanks for the detailed explanation.  I had actually expected something like this to be the case and to be honest I am not sure what the answer is either.  
Generally speaking though, I find that when I need the wares, I need them in any quantity available.  However, because it takes so much time to get from point A to B, going to get 10 hull parts when you can carry 300 is kind of ridiculous.  Conventional wisdom would be to wait until there were 300 available and that would work IF you could reserve future production i.e. put in a order for 300 hull parts at the factory, then when they have your 300, they signal you to come get them.   The problem though it doesn't work that way and I find that the galaxy economy is always in a constant state of supply shortage. IN most cases you will never see a stockpile of 300 hull parts before some NPC has grabbed them, which means you missed out on the 149 that were produced while you were waiting for the that magic number of 300 for a full load.
That being the case, I would lean toward some way of allowing lower volumes so you don't miss out on smaller amounts when you desperately need the product.  At the end of the day, I would rather have 149 hull parts than zero.   
Just my thoughts.


    On Tuesday, April 6, 2021, 09:03:37 AM EDT, Brian Hayden ***@***.***> wrote:  
 
 


So the way it used to work was that the max trades option effectively changed the minimum trade size.... with a default setting of 5, that meant that supply mules would allow trades that were only 20% of their cargo.

However, we found that after a major refactoring of our code, the max trades setting was causing a bug, where after the first trade was queued up, the game would cancel our aiscript and relinquish control to the trade orders that were created. So I fixed max trades to 1 as a workaround, because we don't know a fix for sure for that one.

So then with the setting at 1, of course some trades can just never be completed because the wares don't fit into the cargo hold with an even number. So then I fixed the setting at 75% of cargo.

The only true workaround now is either an "allow low volume" option, like the station mule has, or just a slider, like the travel mule has. I am leaning slider as I tend to prefer giving the user more options.

Changes to params are somewhat major changes and so I've been dragging my feet on this one. I suppose at this time I am leaning towards deprecating the max trades setting altogether and rethinking it at a future date, if both @Galaxy-Spam and myself ever dive deep back into writing code.

**Comment by Chh2tx** [comment]
I've just resorted to using varying sized ships in my fleets. To accommodate for different capacities or ware needs. So a S Frog will capture a really small order that a M or L won't fulfill. Doing so keeps the cargo holds full. So just have to think about where you want your inefficiencies or risk to remain. Full but fragile S traders or near empty L traders?

It's likely more logical, though we often get to a point we want to throw the larger ships at everything. It also makes me think more about securing their pathways for travel and putting more thought into restricting sectors or trade to keep smaller traders safe as well as restricting wares to certain fleet comps, as otherwise, your S traders will still occupy themselves with high profit trades first, and the small ware trade only gets fulfilled once the higher profit/full cargo trades are fulfilled. For example, no station I have ever needs large amounts of MREs or Med Supplies -- most need well under M capacity, so I use S traders for these and restrict M/L traders to not deal with these wares more likely in low volume. Then I created a High Tech Fleet, and it has varying ship sizes from L to S now. They all will prioritize full supply loads first, but when demand starts to dry up and the Ls and then Ms no longer have appropriate trades the S will finish up the low hanging fruit. 

I'm still not using warehouses/trade centers yet so there may be more effective means. I mainly use some supply fleets in various wares that their entire job are to serve my stations. If the station has a consistent demand that's always present than I will assign a supply mule of appropriate capacity to the station and he takes that burden off the unassigned fleet.

That said, you could manually edit the supply_mule.xml to change the fill % to something you desire for now, and perhaps down the road we get some choices or a slider that allows for more flexibility. I've just countered by diversifying capacities within a fleet. 

`<set_value name="$minCargoSize" exact="0.75*($ShipCapacity)f / $maxTrades" />`

I still would counter that a prioritization of low stock ware may be desirable over just max profit. I often see the issue with my Shipbuilders, that for Terran need Microlattice, Silicon Carbide and Computronic Substrate. If I expand and queue up ships, they'll put a big dent in the wares in stock. So the traders start to replenish, but due to the nature of the ware cost -- if you're out of stock on a less costly ware, you'll be sitting waiting for the higher priced ware to replenish before they swap to the next one. This keeps the shipbuilder out of commission for longer. It'd be interesting if there was logic to say while x is max profit, the station has critical demand for y. Since both meet my cargo restriction, I'll fulfill the critical demand first. This would help restart production lines IMO. Just a thought, but not sure complexity to implement something like that either and being a user option.

**Comment by bhayden53** [comment]
It might be possible to do an option like "prioritize stock levels" which would then change the objective function to prioritize low stock.

I am thinking that I will do a cargo level slider for supply mule though. I am also finding times where I'd like to use it; one such example is for traders trying to supply wares for research. You basically can't use a medium supply mule the volumes are so small. I find myself using small vanilla traders for those.

**Comment by Midnitewolf** [comment]
Sounds great.  For the most part I have figured out how to get them all working and now that I know why they don't work, when they don't work, I am not getting stressed and frustrated trying to figure out why they aren't working.  X4 is a great game but much of what I find myself doing is always trying to figure out why something isn't working like everyday common sense says it should be working.  Whomever designed the commands, menus and interface must have been smoking crack at the time they did it hehe.
Hey off topic.  There is an abandoned mod on the Nexus I am desperate for.  It is called "Immediate Orders" which adds a bunch of commands to the right click menu that will cause a ship or fleet to delete all previous orders and immediately execute the new orders, things like "Attack Now", "Fly There Now, Protect this area Now, etc.  Is there any way you might be able to resurrect it?
I tend to try to command Fleet engagements like a RTS without pausing every 5 minutes to issue orders, I just want my ships to go and do what I want, without having to worry about forgetting I had an previous order qued up causing everything to fall apart.   I am sure others would be interested in this too.
Ok enough begging.  Thanks for listening and absolutely thanks for your feedback.
Ben
    On Saturday, April 10, 2021, 11:08:51 PM EDT, Brian Hayden ***@***.***> wrote:  
 
 


It might be possible to do an option like "prioritize stock levels" which would then change the objective function to prioritize low stock.

I am thinking that I will do a cargo level slider for supply mule though. I am also finding times where I'd like to use it; one such example is for traders trying to supply wares for research. You basically can't use a medium supply mule the volumes are so small. I find myself using small vanilla traders for those.

**Comment by bhayden53** [comment]
The problem with immediate orders is that it's a gui mod that's dependent on very old methods of hacking into the gui. I really have no experience with lua or the gui code, except that it's pretty likely to break on game updates, much more so than aiscripts.

You might ask in the x4 discord if there's anyone willing to resurrect it.

**Comment by Misunderstood-Wookiee** [comment]
Orders mod is outdated but it may work Sirnuke api supports the old method
built in.

**Comment by Vectorial1024** [comment]
Getting a bit off topic, but Civilian Fleets used to require Right Click API in their earlier version, and later transitioned to SirNukes API to be more stable throughout the update process, so resurrecting ImmediateOrders should be very much doable.

**Comment by bhayden53** [comment]
I'm sure it's doable, I'm just saying, I'm not doing it :)

**Comment by Midnitewolf** [comment]
Too bad.  Thanks for thinking about it for a second at least hehe.


    On Tuesday, April 13, 2021, 08:52:04 AM EDT, Brian Hayden ***@***.***> wrote:  
 
 


I'm sure it's doable, I'm just saying, I'm not doing it :)

**Comment by Vectorial1024** [comment]
And someone else did it!

https://www.reddit.com/r/X4Foundations/comments/mslahr/new_mod_urgent_orders/?utm_medium=android_app&utm_source=share

在 2021年4月14日週三 00:14，Midnitewolf ***@***.***> 寫道：

**Comment by Misunderstood-Wookiee** [comment]
Status of the issue at hand?

**Comment by Misunderstood-Wookiee** [comment]
> Right Click API

Yeah that support IRC is/was built into SirNukes API for backward compatibility, I see we have moved past all this so closing this issue.
