### ISSUE TITLE
[QUESTION]: Not sure if a bug or if I'm setting something up wrong.

### ISSUE THREAD

**Issue by bandus** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#117]
> Check available  [Informational Material and F.A.Q](https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/blob/Public/README.md)  before posting.

**I would like the know the following:**
I have read the instructions and the forum post and I am still having some confusion. My situation is this: I have 1 station that is intended to be a warehouse. It is comprised of 2 Terran Hex Docks, 1 Terran Luxury M/S dock, 21 Terran L Container storage units, and some defensive bridges and platforms. 

In close proximity (as in, within 20km), I have multiple production factories (Solar Power, Computronic Substrate, MRE/Medical Supply, Silicon Carbide, and Metallic Microlattice). 

I started by determining 1 transport, per factory (minus the warehouse), that would be assigned to each. I took went into the behaviors tab of each ship and setup them up as follows: 
<img width="545" alt="X4001" src="https://user-images.githubusercontent.com/4082682/116007297-b730a380-a5d4-11eb-91bf-98e9be178fe7.png">

In each case, a buy order was created on the warehouse for the corresponding good *except* in the case of MRE/Medical supply station. In that case, no buy order was created for Terran MREs/Medical supply wares. 

I'm honestly not sure if I'm doing something wrong with the setup of this mod in general, etc. I was wondering if someone would be willing to try to assist me?

Also, does there happen to be a Discord for this mod where one might get help with it? Thanks!

**Comment by bhayden53** [comment]
The original author had hardcoded some of the food/med wares, and I wonder if that's somehow causing the problem with creating the trade ware on the warehouse; but I have been using the station mule successfully to move terran food/meds. 

I actually haven't been using "make target warehouse" as much now, since on the warehouse you can add the ware as a tradeware yourself through the logical overview. I tend to want to manually setup trade rules and buy amounts so I am pretty micro-managing on that aspect. 

I will try to take a look into why make target warehouse isn't setting those; my first guess though, is if you have hab modules on the station, the mre's and med supplies are actually seen as needed for production, and so perhaps they aren't classified as a "trade ware" anymore on that station. 

You can go to the "x4 modding" channel on the official egosoft discord and ping me as drhay53 if you want help that way.
