### ISSUE TITLE
[Potential Bug]: I think I found a bug!

### ISSUE THREAD

**Issue by DeathDealer862** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#128]
>Please check for an existing issue before making a new report and comment in that report if one exists.

**Describe the Bug**
my trader go out sector and sale to AI

The log file 
ScriptStart
Ship: X-Sector Supply #2 (QAH-804) - 0x2e463
AssignedControlled: X-Sector Supply #2 (QAH-804) - 0x2e463
Entity (this): 0x2e469
Supply Mule Settings:
    Home: Heretic's End (null)  < home sector
    assignHome: 0
    maxDist: 0  < max distance is 0 mean stay in my sector only
    dedicatedServe: 0
    allowPlayerSuppliers: 1
    allowAiSuppliers: 0  <----- ai off 
    allowBuildstorage: 1
    allowResources: 1
    allowIntermediates: 1
    allowTradewares: 1
    lockWares: 0
    specialWareBasket: [ware.advancedcomposites,ware.advancedelectronics,ware.antimatterconverters,ware.dronecomponents,ware.energycells,ware.engineparts,ware.fieldcoils,ware.foodrations,ware.hullparts,ware.medicalsupplies,ware.missilecomponents,ware.scanningarrays,ware.shieldcomponents,ware.smartchips,ware.turretcomponents,ware.weaponcomponents,...]
    maxTrades: 1
    playerBuyMod: 100
Home Station or Ship: -
Home Sector: Heretic's End
trying to sell 1458 Advanced Electronics from cargo
  found buyer: ownername: FRF Split Trading Station(Free Families), unitprice: 101300, amount: 17750, relative price: -0.00328946, totalprice: 1798075000, sector: Tharka's Ravine XVI, gates from this ship: 8, gates from home (from ship if not homebound): 8. selling amount: 1458
  trade created
******* went to end

**Version Info (please complete the following information):**
 - X4 Foundations : [4.0.0.0 Hotfix 3 ]
 - Mules Extended Mod : [e.g. v.6.3.3 ]
 - I downloaded the mod from: [Workshop]

**Comment by Misunderstood-Wookiee** [comment]
@bhayden53  handles most the code side but the allow ai suppliers off.

Which I don't think stops you selling to them only it won't buy from them.

**Comment by bhayden53** [comment]
he triggered the "cargo emptying" routine which means at some point, he ended up having his order reset (by the game) in the middle of attempting a delivery. It happens from time to time and isn't much of a concern.

The only alternatives are to let the mule sit there doing nothing because he has random cargo in his hold, or dump the cargo.

**Comment by Misunderstood-Wookiee** [comment]
I may a way around this
But it's not exactly fair lol

**Comment by bhayden53** [comment]
the cargo emptying routine triggers very rarely under normal conditions, and if it does happen, it's usually because player storage is so full everywhere, that there's almost nothing valuable to do. It's not worth spending much time on, to be honest, and you're right that the "allow ai suppliers" doesn't really come into play here.

The basic idea is to dump the stuff in the hold as quickly as possible so the mule can get back to work.

**Comment by Misunderstood-Wookiee** [comment]
Yeah that ai tick box can be done with trade rules any way as I swear it
just bans mule from buying from AI.

I did msg you in Discord chat but ill remind here im getting the dev ready
into the wild tonight.
