### ISSUE TITLE
[QUESTION]: Regarding Numer of Trades option slider

### ISSUE THREAD

**Issue by shadowfax13th** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#153]
I have never seen this slider not grayed out. I've read the instructions and looked around but can't figure this at all. Could anyone please give me a hand? My biggest problem is choosing the right % for cargo space fill, especially when using large freighters.. If I set it too high then they won't do anything because who's gonna buy a Buffalo or worse a Sanahar full of anything? If I set it too low then   then I have all these freighter running around carrying a Baldric's worth of cargo. If I could get the slider to unlock then they'd take more than one trade and fill the hold right?

Any help would be appreciated, thanks for your time.

I should mention, to figure out if it was a Pilot level issue I even cheated max level to see if this opened the slider, it didn't.

**Comment by bhayden53** [comment]
That option was broken after we refactored the code, and I disabled it by fixing the value to 1, but I left it as a param so as not to break existing saves when the update came out. I should probably look into whether I can hide it completely or not. It absolutely does not work for any value greater than one anymore.

If you have large ships carrying small amounts, that's because that's the best trade they can find. You do have to go around every once in a while and make sure all your ships actually have something to do. If they don't it typically means you've got too many doing a specific job, and you should rotate some out somewhere else. For instance, I like to have a combination of mule and tater trader mimic fleets setup. Every once in a while I'll check on them and find that one of the fleets has a lot of ships with nothing to do. I'll peel all of the ones that are searching for trades off and give them something else to do. Sometimes that means "well it's time to build a new station" and sometimes it's just "let's assign them to <xyz> wharf to help out that faction". 

I do typically set my large freighters to 25% cargo these days. In fact, I pretty much do that with all sizes. Because there comes a point where I just don't feel like micro-managing all of my traders anymore. Since the supply mule picks trades based on total amount of "profit", even if it's running a small amount, that's because there's nothing better to do. If you see that, you probably need to provide more for them to do (by building something, for instance!)

**Comment by shadowfax13th** [comment]
Setting the % of hold to fill, that isn't a x% or greater value is it? If they have the option of filling the hold beyond if the opportunity presents then I can live with that, and I agree with what you were saying... I'll just have to shuffle ships. But if there's at least a chance for them to go over  know that if a need comes up they'll fill it efficiently.

And thanks for the quick reply!

**Comment by bhayden53** [comment]
The x% is the minimum amount of the trade. Sorry if I misunderstood the original question.

It means "a trade is only valid if it fills the hold at least x% full"

**Comment by shadowfax13th** [comment]
I might have worded it weird. But knowing the the x% is a => kind of setting makes me much happier. Much happier. Thank you for letting me know.
