### ISSUE TITLE
Supply mules don't respect max jumps in some cases.

### ISSUE THREAD

**Issue by art4711** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#41]
I'm seeing a lot of my supply mules not respecting the max jumps setting in some (all?) situations.

To clarify. I have in my universe a system set up for providing everything for a shipyard. It's 15 stations and the cluster is perfectly self sufficient. Yesterday I copied the exact setup of stations to another system on the pretty much other end of the galaxy (Company Regard vs. Tharka's Cascade). Each station has a few supply mules each set up with a source station, assign ship to station, serve source only, player suppliers only, max jumps 1. Yet supply mules both from the old system and the new system are running across the universe to fetch stuff even though the exact same wares are right next to them.

I've been trying to wrap my head around the script and the whole scripting language in general and it looks to me that some find_sell_offer have explicit distance and blacklist handling, while others don't. I copied the blacklist and distance handling from other find_sell_offer calls to the ones where I think it mattered and that seems to work, but I'm not exactly sure why things were done the way they were and what the actual design intent is, so I'd rather leave it up to you to figure out where they should go.

It's actually pretty funny to watch the traffic jam this has created (I'm counting 48 of my freighters just in two systems between the production systems), but I'd rather not need to quadruple the storage and build another 400 freighters just to make this whole thing work.

Btw. Reconfiguring all the mules to change their max jump setting in the first system was a real pain, but it looks to me that if a ship is assigned to a station (or any other commander) changing order params is locked and I can't find a way to unlock it.

**Comment by Vectorial1024** [comment]
The station assignment feature is related to #22 .

You may use mods such as Subordinate Order Access https://www.nexusmods.com/x4foundations/mods/289 to modify the orders of the subordinates when needed (such as your case where you need to adjust the Station Mule parameters of ships having been assigned to stations).

**Comment by art4711** [comment]
> You may use mods such as Subordinate Order Access 

Cool. That actually worked, thanks for the tip. Of course, just like every other mod that uses G workaround that I've tried it worked and then broke something else so I had to disable it, but I could enable it long enough to fix the settings on 200 ships.

**Comment by bhayden53** [comment]
Apologies for the confusion here but if you look at the README on the repo it says this:
```Max Jumps - in general when considering player to player trades there is no maximum jump distance. However, when sourcing from the AI or serving AI stations, this distance is obeyed. This is based on pilot skill.```

I chose to do it this way because I thought it would be more frustrating as a user to have difficulties connecting your stations. However I do realize this is not optimal, because it means sometimes your  supply mules will be running all over the place when you really don't want them to.

The way I look at it is something like:
If I want a mule to do something really specific, I use station mule or distribute mule.
If I want a mule that never idles and just picks up a lot of slack, I use supply mule.

In my own save, I have about 15 production stations feeding 3 warehouses. Each production station has a single station mule and a single supply mule, all mediums. That handles basically all of my needs. On my shipyard and wharf, I have ~10 M supply mules and 5 L supply mules. I also leave 5 supply mules on build storage only so that they swarm my builds as soon as their script restarts. 

Anyway I haven't come up with a better solution yet; I thought users would be more likely to accidentally misuse the supply mule if the jump distance was used for player-to-player trades.

**Comment by art4711** [comment]
I tried a setup with a warehouses, but couldn't setup a second warehouse because distribute mule didn't want to distribute there unless there was a buy order and as soon as the second warehouse ran out of stock it removed the buy order. This was a few weeks ago and you've changed and fixed things since then so maybe I should give it another go in the next game (I just decided my current game is over when ordering 50 Raptors at my shipyards without having to wait for wares, Xenon and Split are dead and the FPS drops below 5 when I open the map). Or maybe just building an empire in one cluster of systems and not spreading out over the galaxy is a solution too.

I figured that a system that will scale the best is where each station is responsible for getting its own resources. Build station, give it a handful of supply mules and I only need to reconfigure them once when they don't need to fetch supplies from NPC stations anymore and by building stations in the right order this step can be skipped. Compared to station mules that each would need to be reconfigured every time a new consumer is built. But maybe warehouses are the answer. Such a traffic jam nightmare though.

**Comment by bhayden53** [comment]
You don't need to do anything to get supply mules to switch to prioritizing your own supply; they'll do it on their own as soon as the player supply exists.

One thing to reiterate; every station in your empire must have a manager for orders to work properly.

**Comment by Misunderstood-Wookiee** [comment]
> Of course, just like every other mod that uses G workaround that I've tried it worked and then broke something else so I had to disable it, but I could enable it long enough to fix the settings on 200 ships.

You don't have to use Gworkaround anymore, SirNukes Modding API is far superior and his LuaLoaderAPI (which is included) will auto-detect and load any old Gworkaround registered mod according to him, as I asked him about this because I was going to change a mod to register with his but found out soon after asking it is not necessary.

Hope this tid bit is also useful.

**Comment by Galaxy-Spam** [comment]
The behavior in the refractored supply mule code currently does take jump gate distance for all cases into account. If it stays like this, we can probably mark this as "fixed" anyway.

**Comment by petethehut** [comment]
> 
> You don't have to use Gworkaround anymore, SirNukes Modding API is far superior and his LuaLoaderAPI (which is included) will auto-detect and load any old Gworkaround registered mod according to him, as I asked him about this because I was going to change a mod to register with his but found out soon after asking it is not necessary.
> 
> Hope this tid bit is also useful.

Hi,
so I can just install a mod with Gworkaround dependency an it will work?

**Comment by bhayden53** [comment]
I asked Sir Nukes on the discord and he said generally there is at least a little work that needs to be done to make the mod compatible with both.

**Comment by bhayden53** [comment]
Fixed in the next release
