### ISSUE TITLE
Using Large/XL Mining ships as a mobile base?

### ISSUE THREAD

**Issue by FormBurden** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#67]
So I saw a comment about someone wanting to use an XL ship (even a L should could work in theory too, really anything with a dock) using the Mod XL Mining Ships Mod and having the ship pretty much be a mobile dock while having smaller mining ships transport the goods to a station, using a mod such as Mules or TaterTrader. I ended up helping the person but didn't realize you couldn't have the assign feature (the source) to a ship, so really you can't do such a thing. I know that the team has been adding features for using Mules like Supply Mules for Miner ships to trade those wares from people suggesting it. But what about the above? 

Is it possible to have a feature such as the source when you assign a mule to a source station, to work similar (or through a different button) and the mule could be assigned to a big ship like these to trade the goods. 

An Example of this chaotic idea:

XL/Large Miner (or anyone with a deck) be out in space, mining or whatever >>> Then you have a Miner-trader dock with the ship, grab the goods, then go out and sell, and repeat. Anyway, something like that.

There are some issues I've seen with even the vanilla game that conflicts with this crazy idea (not the above).

1. I would like to see smaller miners dock with the XL/L miner to give the goods to them, but it seems as through there is no feature for vanilla scripting. Maybe a mod could do it?

2. With Civilian Fleets, you can assign a miner (smaller miners) to the large ship and they'll do their thing, but you cannot assign a trader to the Large Miner. Mainly because it's not a station, and the code most likely isn't in the mod anyway for such a thing. Idk if you could even do it through modding?

Anyway, just throwing some crazy ideas out here to see if it's possible or not, and from the persons comment.

**Comment by Vectorial1024** [comment]
Regarding 1 about the ai orders, the hint should be the "transfer wares" order. If we issue the transfer wares order in the script, then the ships should be able to dock at the big miner and take away the wares. Not sure if it will stop the big miner from mining because of the "waiting for xxx" state.

Regarding 2 about Civilian Fleets, you could assign miners to other miners using the trade job, so when the leader miner is trading minerals, so will the members of the fleet. Of course, no one currently will need to trade minerals...

So, we could make a new script/modify an existing script to tell small miners to go transfer wares with the big miners, or we can make a new mining script for big miners to issue trade offers at the big miners so small miners can buy stuff using e.g. the AutoTrade order.

**Comment by bhayden53** [comment]
This sounds like a new mod to me, rather than an addition to mules.

**Comment by Vectorial1024** [comment]
A quick look of the game source files suggest that there is a workaround:

Build a warehouse with bulk storage, add minerals as trade wares, then assign miners to the warehouse. The miners running the AutoMine will notice that the warehouse will want minerals and then start mining nearby.

**Comment by bhayden53** [comment]
I have had some problems getting the miners to actually work. I suspect it's related to the issue we've been seeing with warehouses where they need astronomical budgets for their trade orders to consistently exist. If the budget is too small, as soon as a reservation goes out, all buy orders are locked down. We don't even receive them from find_buy_offer anymore. The budget needed on a warehouse goes into the 10's of millions before you stop seeing this. 

I have tried using miners on a warehouse before, even with some budget, and they just sat around "free mining". It's worth testing, but I've had some problems getting it to work.

**Comment by FormBurden** [comment]
Ah I see. Yeah, from Vectorial1024 comment, I have had a warehouse that is just for mining and then you assign Mules or TaterTraders to the station and they'll trade, but haven't really done it since the previous issue the two teams have been addressing with the traders getting turned into miners for some reason. I did a trial run and it seems to be fixed, but haven't really done it since in general like I did before.

**Comment by Misunderstood-Wookiee** [comment]
If this is somehow related to that time I was on X4 Discord and suggested using an L or XL class as a means to use the docking bays to dock class S as a trader or miner for the L or XL and basically the larger craft would act as a maintenance and staging carrier and find orders for a fleet of smaller ships who instead do all the moving of the wares to and from the carrier.

That was something I thought about doing by using a ship out of the carrier-class that acts as a non-military retro-fit carrier and is fitted for trade and cargo haul not combat to carry the docked ships that can go off and mine and trade for it, while it you basically just park it somewhere order it to find auto trades and it will relay orders it finds to the small fleet it carries and these do all short-range travel. I had a concept for this to use the station trader type fetch needs and the carrier would simply be the one to supply the needs while all subordinates of the said carrier would be assigned as traders for it. 

However this very much indeed is a separate project.

This could not too hard to implement.

**Comment by Vectorial1024** [comment]
What I have in my mind recently is a new default order, something like "Mobile Trading Station".

This default behavior will require a list of wares as the only parameter.

What it does is that it will post trade orders of those wares, and that's it.

Maybe it will run away a little if attacked, or mine the minerals if there are minerals in the ware list, but other than that, it posts trade offers and nothing else.

This should allow implementation of of the "mobile mining base" idea quite cleanly.

**Comment by Misunderstood-Wookiee** [comment]
Seems like something vanilla should have probably been able to do already.

This did remind me though I had a complex way to make xl ships useful as above and a more simple way.

Currently you cannot assign a small shop to trader on another ship I was going to change that and setup kinda like you suggested where the xl ship will make trade offers to sell its cargo like a station would then any assign subordinate traders should in theory see these as valid buys and go well them within range I was thinking of doing the same with miners so that you can assign mine for using the vanilla options this size S or M miners and traders can be assigned proper roles to the larger ship with appropriate pad and basically work directly off the ship which seems to me like an oversight on ego part as that whole mechanic makes it possible for courier plus xl trader or l trader, or l miner plus S miner combinations which especially since mods like VRO add more pads you could effectively use a supply ship as a mobile base and park it then send out like 20 miners who mine then dock and or traders to go find deals remotely, or you can have a large miner coupled with a miner set to trade for then it can stay mining and the small miners can offload it's cargo around the place short range style which is way faster then sending the xl ships to dock.

**Comment by bhayden53** [comment]
I'd like to close this issue as I really think it's beyond the scope of mules, at least in my vision. But I'd like @Misunderstood-Wookiee and @Galaxy-Spam to chime in

**Comment by Misunderstood-Wookiee** [comment]
Fine with me, it's more a discussion at this point.

**Comment by Galaxy-Spam** [comment]
For me it's sound like a seperate mod.
Probably, you could restructure a supplyship and allow let it create trade offers using orders (like @Vectorial1024 said).
It sounds like an easy mod, but i would not consider it a mule with this kind of an implementation.
I would recommend a seperate mod and just use travel mules/traders to sell/transport stuff of the ship.

**Comment by bhayden53** [comment]
Think it's a cool mod idea if anyone ever gets time to work on it, but closing as part of general issue cleanup.
