### ISSUE TITLE
Deadair's Gate Overhaul Issue

### ISSUE THREAD

**Issue by mdmueller2316** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#69]
Hey guys, me again. 

It seems that when running dozens of supply mules on the massive map (https://steamcommunity.com/sharedfiles/filedetails/?id=2082610651) I begin to get consistent stutters of around 1 second or more. I noticed it was happening more and more often the further I got into my game, so I thought it was an issue with gate overhaul. Eventually it caused me to rip out all my mods and plug them back in one at a time to see what was causing it. It turns out it was the supply mule. I could easily reproduce it by adding and removing the supply mule default action. 

Thought you'd like to know.

**Comment by bhayden53** [comment]
Most likely this is due to very large buy/sell offer search spaces when there are so many gates. In the current version of mules, for player to player trades there is no check for distance, so I suspect the mule is searching the entire universe for player stations.

In the release that's upcoming for X4 3.2, the supply mule always obeys the max distance setting, so hopefully that means this won't be an issue. If it still is, please come back and let us know!
