### ISSUE TITLE
Mules Overhauled mod

### ISSUE THREAD

**Issue by AqlaSolutions** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#70]
Hi, big thanks for your mod. I had to make some changes, then more and more and now there are too many of them to pull request. So I released them separately here https://www.nexusmods.com/x4foundations/mods/512 , please read the description for the full list of changes. I mentioned you in credits so I hope it's ok.

If you'd like to take something into your mod here is the github link to compare changes https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/compare/Public...AqlaSolutions:Public

**Comment by AqlaSolutions** [comment]
Unfortunately I didn't know about your public beta or I would use it as a base instead. I really like your refactorings but too late ((

I checked your changes and it turns out that you should be able to merge all my changed mules except SupplyMule. You might want to manually reapply some of its changes to your code base.

Created pull request for TravelMule https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/pull/71

**Comment by bhayden53** [comment]
Anything that uses tradeoffer.restriction.faction will break in 3.2, as it was renamed to tradeoffer.restriction.factions with the addition of trade rules. We made the decision not to apply trade rules to the station mule yet, since the player sets both destinations in the UI. Technically the player could blacklist themselves and then the station mule would generally have nothing to do, but I'm trying to strike a balance between supporting Egosoft features and not letting the player screw things up that result in Steam comments that take forever to debug.

Personally, I would prefer you to contribute here rather that release a new mod, but obviously I can't stop you due to the licensing.

**Comment by AqlaSolutions** [comment]
@bhayden53 I didn't know about 3.2 changes, then of course there is no point to merge other mules.

I would prefer to contribute here too but it's too late to redo everything with beta. If you feel like there is something useful for you in my version of SupplyMule go ahead and copy it.

**Comment by Misunderstood-Wookiee** [comment]
`late to redo everything with beta.`
That is probably what the original author thought before we took it over, the v4 and other forks of such are so far out of date now I doubt even the basic mules work.

I mean feel free attempt to make necessary changes and PR into branch dev, of course, it is up to you if you wish to do that or go your own path. 3.2 changes things which simply would not allow us to merge anything else into public. 

Currently, most of the work is done in the dev branch 
the Beta branch is a periodic snapshot of dev, I know I would like to merge stuff from public beta into an official release too but 3.2 really changed a few things which make it not possible to run the trade code so I guess its a waiting game with Egosoft atm.
