### ISSUE TITLE
[QUESTION]: Setting up a depot

### ISSUE THREAD

**Issue by feltech** [Misunderstood-Wookiee/Mules-and-Warehosues-Extended#92]
As mentioned in https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/91#issuecomment-690769670 I am trying to set up a depot.

I use the word "depot" rather than "warehouse", because I _think_ the use case is a little different, e.g. I specifically don't want to "Make Target Warehouse", from what I can tell from the docs.

I want to transport a specific set of wares (missile construction) from my complex several sectors away to a Defence Platform.  I would then like use the Defence Platform to supply trade offers in the same sector (i.e. Auxiliary ship).
 
The platform has storage.  I have added the wares as "Trade Wares" in the Logical Overview.  But neither Station nor Distribution Mules do anything, they just sit there "Searching for trades".  

I tried setting the Distribution Mule "Static Storage" to a really low number (5%) - I definitely have more than that for all wares in the source.  I transferred a small amount of those wares to the platform to see if that would get the ball rolling, but nothing.

Then there's the question of whether the Supply Mules will actually use that station, once it has wares onboard, as a source, but I've not got that far yet.

Any hints?

**Comment by feltech** [comment]
Having just wrote all this, I _think_ I may have solved it.  I tried a Station Mule with "Allow Low Volumes" and he set off to work.  

That seems to correspond with the "sell amount" setting in the Logical Overview of the factory, that is, for all but one of the wares... still investigating but looks like I may have solved it.

**Comment by feltech** [comment]
Woohoo, just saw a Supply Mule go to the Defence Station to get Energy Cells for my Auxiliary ship.  So I think all sorted.  I'll close this (rather short-lived) issue.

**Comment by bhayden53** [comment]
Glad you were able to work through it. The usual suspects for users are "does the station have a manager and funding?". Because ultimately the mules are still dependent on orders being created, which requires those two things. It could be that the reason you need low volume is due to lack of funding? A while back someone took a look at forcing trades by looking at storage levels rather than trade offers, but due to many factors (mostly the game API), I think it's likely to be a really hard project that's prone to bugs.
